services:
  nginx-proxy:
    profiles:
      - nginx-proxy
    container_name: shared-nginx-proxy
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # Public HTTP Port (8080 to avoid conflict with Laravel Herd):
      - '127.0.0.1:80:80'
      # Public HTTPS Port (8443 to avoid conflict with Laravel Herd):
      - '127.0.0.1:443:443'
      # Admin Web Port:
      - '127.0.0.1:81:81'
    environment:
      # These are the settings to access your db
      DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - shared-development
