services:
  ngrok:
    image: ngrok/ngrok
    restart: unless-stopped
    volumes:
      - ../ngrok.yml:/ngrok.yml
    ports:
      - 4040:4040
    command:
      - "start"
      - "--all"
      - "--config"
      - "ngrok.yml"
    networks:
      - sail