services:
  ngrok:
    image: ngrok/ngrok
    restart: unless-stopped
    volumes:
      - ../ngrok.yml:/ngrok.yml
    ports:
      - 4040:4040
    environment:
      - NGROK_CONFIG=/ngrok.yml
    networks:
      - sail