services:
  ngrok:
    profiles:
      - ngrok
    container_name: shared-ngrok
    image: ngrok/ngrok
    restart: unless-stopped
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    volumes:
      - ../ngrok.yml:/ngrok.yml
    ports:
      - 127.0.0.1:4040:4040
    command:
      - "start"
      - "--all"
      - "--config"
      - "ngrok.yml"
    networks:
      - shared-development