services:
  ngrok:
    image: ngrok/ngrok
    restart: unless-stopped
    # command:
    #   - "start"
    #   - "--all"
    #   - "--config"
    #   - "/etc/ngrok.yml"
    volumes:
      - ../ngrok.yml:/ngrok.yml
    ports:
      - 4040:4040
    environment:
      # - NGROK_AUTHTOKEN=your_ngrok_authtoken
      - NGROK_CONFIG=/ngrok.yml
    networks:
      - sail