services:
  redis:
    profiles:
      - redis
    container_name: shared-redis
    image: 'redis:alpine'
    restart: unless-stopped
    ports:
      - '127.0.0.1:${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - './shared-redis:/data'
    networks:
      - shared-development
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    command: "redis-server"
    # command: "redis-server --requirepass ${REDIS_PASSWORD}"